# Generated by Django 3.0.2 on 2020-01-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('account', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('status', models.IntegerField()),
                ('date', models.DateField()),
                ('ref_name', models.CharField(max_length=150)),
                ('ref_number', models.IntegerField()),
            ],
        ),
    ]
