# Generated by Django 3.0.2 on 2020-01-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200127_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref_number',
            field=models.BigIntegerField(),
        ),
    ]
