# Generated by Django 3.0.2 on 2020-01-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200127_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetail',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
