# Generated by Django 3.0.2 on 2020-01-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_loandetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
